gxt -g VC -i "american.txt" -o "C:/gta-extended/bin/win-x86-librw_d3d9-mss/Debug/TEXT/american.gxt"
gxt -g VC -i "french.txt" -o "C:/gta-extended/bin/win-x86-librw_d3d9-mss/Debug/TEXT/french.gxt"
gxt -g VC -i "german.txt" -o "C:/gta-extended/bin/win-x86-librw_d3d9-mss/Debug/TEXT/german.gxt"
gxt -g VC -i "italian.txt" -o "C:/gta-extended/bin/win-x86-librw_d3d9-mss/Debug/TEXT/italian.gxt"
gxt -g VC -i "spanish.txt" -o "C:/gta-extended/bin/win-x86-librw_d3d9-mss/Debug/TEXT/spanish.gxt"